[package]
name = "egov-document-simplepush"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
env-file-reader = "0.3.0"
gotify = { version = "0.4.0", features = ["app"] }
regex = "1.11.1"
reqwest = "0.12.9"
tokio = { version = "1.41.1", features = ["full"] }
